### ISSUE TITLE
Connection to internet services

### ISSUE THREAD

**Issue by jjeising** [JustAman62/ovault#1]
Hi, ovault looks great so far! I found a small issue with the claims and the the implementation.

On ovault.net it says:
> 100% on-device processing and storage. **OVault contains absolutely 0 connections to internet services**

The App Store page says:
> - 100% local-only processing. **No data (not even usage data) is sent to any services** outside of your iCloud Keychain (if enabled on your device).

As far as I understand this is in conflict with the usage of logo.dev:
https://github.com/JustAman62/ovault/blob/0e521cd5aaf2c6f1af9d081ddc8f98e85fef1d84/Models/Otp.swift#L58

This would send all used domains, even these of internal services, to an external commercial service. As I don't see any kind of caching this might also expose usage, as the images may be loaded every time the view is displayed.

**Comment by JustAman62** [comment]
Yep that’s a very valid catch, thanks for raising! 

FWIW, providing domains is optional when creating OTPs, and Swifts `AsyncImage` (which is used to display these images) should implement image caching as it uses `NSURLSession` to load them. So I think the user has sufficient control over this indirect usage leak.

Nonetheless, this should be fixed:

- [x] Update the language on the site and App Store page to indicate the usage of logo.dev. 
- [x] Add language to the app clarifying the optional nature of domains, and double check we prevent calling logo.dev when domain is empty
- [ ] Implement manual caching for images to ensure we don’t leak usage data to logo.dev explicitly, rather than relying on `AsyncImage`s caching

Hopefully I’ll be able to get around to this in the next day or two.

Please let me know if you think anything else should be done.

**Comment by jjeising** [comment]
Sounds good to me! Wasn't sure about the caching, just had a very superficial look, thanks for clarifying.

Regarding the fixes: As the domain seems to be automatically set for QR codes
https://github.com/JustAman62/ovault/blob/0e521cd5aaf2c6f1af9d081ddc8f98e85fef1d84/Models/Otp%2BFrom.swift#L46-L47
(which may also be a problem, if the issuer contains spaces?), maybe a global option to disable use of logo.dev might also be helpful?

**Comment by JustAman62** [comment]
Good idea. I've pushed a build to App Store review which adds a setting for Domain Icon loading from icons.dev (defaults to off) (da86bf78fa9c8ea5cf704728d05a063698667fd0). I've also improved the way we load icons to reduce the number of times we load (only on fetch from Keychain 16bc6a279b1c3e1420c3af395defde2c66a3e153).

We now load images directly with `URLSession`, and I've confirmed that we receive and respect `Cache-Control` headers so that we don't call logos.dev unnecessarily. For this reason, I won't implement custom caching for now.

https://ovault.net has been updated to clarify claims about internet services, and the App Store description will update similarly when the build is approved.

With this I think the issue should be good to close, Let me know if I've missed anything!
